In [22]:
import numpy as np
import pandas as pd

In [23]:
data=pd.read_csv("Messy_Employment_India_Dataset.csv")
data.head(5)

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [24]:
data.isnull().sum()

Status                   268
Age Group                232
Education                196
Industry                 201
Location                 213
AI Risk                  284
Years of Experience     1020
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years of Experience   980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [26]:
data.select_dtypes(include="Float64").columns

Index(['Years of Experience', 'Monthly Salary (INR)'], dtype='object')

In [27]:
from sklearn.impute import SimpleImputer

In [30]:
si = SimpleImputer(strategy="mean")
ar =si.fit_transform(data[['Years of Experience', 'Monthly Salary (INR)']])

In [31]:
new_data=pd.DataFrame(ar,columns=data.select_dtypes(include="Float64").columns)

In [32]:
new_data.isnull().sum()

Years of Experience     0
Monthly Salary (INR)    0
dtype: int64

In [33]:
new_data

      Years of Experience  Monthly Salary (INR)
0               15.244898               40700.0
1               15.244898               17500.0
2               16.000000               77600.0
3               30.000000              100200.0
4                9.000000               19500.0
...                   ...                   ...
1995            15.244898              113000.0
1996            22.000000              102200.0
1997            15.244898               31600.0
1998            22.000000               92500.0
1999            15.244898               43300.0

[2000 rows x 2 columns]