In [30]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder ,OrdinalEncoder

In [31]:
data = pd.read_csv("col_tranform.csv")

In [32]:
data.head(5)

   Age  StudyHours  Attendance  Gender    Stream Passed
0   14           2          85  Female   Science    Yes
1   15           3          78    Male  Commerce    Yes
2   14           1          65  Female      Arts     No
3   15           4          90    Male   Science    Yes
4   16           2          70  Female  Commerce     No

In [33]:
data.isnull().sum()

Age           0
StudyHours    0
Attendance    0
Gender        0
Stream        0
Passed        0
dtype: int64

In [34]:
x=data.drop("Passed",axis=1)
y = data["Passed"]

In [35]:
numeric_coloum =["Age","StudyHours","Attendance"]
categorical_coloum=["Gender","Stream"]

In [36]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric_coloum),
        ("cat",OneHotEncoder(),categorical_coloum)
    ]
)
#syntax = transformername,transformerObject,list['coloums names on which coloum we want to apply']

In [37]:
x_transformed=preprocessor.fit_transform(x)

In [38]:
print(x_transformed.round(2))
print(x_transformed.shape)

[[-1.17 -0.58  0.48  1.    0.    0.    0.    1.  ]
 [ 0.05  0.21 -0.13  0.    1.    0.    1.    0.  ]
 [-1.17 -1.36 -1.26  1.    0.    1.    0.    0.  ]
 [ 0.05  1.    0.92  0.    1.    0.    0.    1.  ]
 [ 1.28 -0.58 -0.83  1.    0.    0.    1.    0.  ]
 [-1.17  0.21  0.75  0.    1.    0.    0.    1.  ]
 [ 0.05 -0.58 -0.65  1.    0.    1.    0.    0.  ]
 [ 1.28  1.78  1.36  0.    1.    0.    0.    1.  ]
 [-1.17 -1.36 -1.7   0.    1.    0.    1.    0.  ]
 [ 0.05  0.21  0.05  1.    0.    1.    0.    0.  ]
 [ 1.28  1.    1.09  1.    0.    0.    0.    1.  ]
 [-1.17 -0.58 -0.39  0.    1.    1.    0.    0.  ]
 [ 0.05  0.21  0.48  1.    0.    0.    1.    0.  ]
 [ 1.28 -1.36 -1.    0.    1.    1.    0.    0.  ]
 [-1.17  1.    0.83  1.    0.    0.    0.    1.  ]
 [ 0.05 -0.58 -0.56  0.    1.    0.    1.    0.  ]
 [ 1.28  0.21  0.4   1.    0.    1.    0.    0.  ]
 [-1.17 -1.36 -1.87  1.    0.    0.    1.    0.  ]
 [ 0.05  1.78  1.44  0.    1.    0.    0.    1.  ]
 [ 1.28 -0.58 -0.22  1.    0.    1.    0.    0.  ]
 [-1.17  0.21  0.22  0.    1.    0.    0.    1.  ]
 [ 0.05 -1.36 -1.18  1.    0.    0.    1.    0.  ]
 [ 1.28  1.    1.01  0.    1.    0.    0.    1.  ]
 [-1.17 -0.58 -0.48  1.    0.    1.    0.    0.  ]
 [ 0.05  0.21  0.66  0.    1.    0.    1.    0.  ]
 [ 1.28  1.78  1.53  1.    0.    0.    0.    1.  ]
 [-1.17 -1.36 -1.53  0.    1.    1.    0.    0.  ]
 [ 0.05  1.    0.92  1.    0.    0.    0.    1.  ]
 [ 1.28 -0.58 -0.74  0.    1.    0.    1.    0.  ]
 [-1.17  0.21  0.31  1.    0.    1.    0.    0.  ]
 [ 0.05 -0.58 -0.3   0.    1.    0.    0.    1.  ]
 [ 1.28  1.    1.18  1.    0.    0.    0.    1.  ]
 [-1.17 -1.36 -1.79  0.    1.    0.    1.    0.  ]
 [ 0.05  0.21  0.13  1.    0.    1.    0.    0.  ]
 [ 1.28  1.78  1.62  0.    1.    0.    0.    1.  ]
 [-1.17 -0.58 -0.65  1.    0.    0.    1.    0.  ]
 [ 0.05  1.    0.83  0.    1.    0.    0.    1.  ]
 [ 1.28  0.21  0.57  1.    0.    1.    0.    0.  ]
 [-1.17 -1.36 -1.44  0.    1.    1.    0.    0.  ]
 [ 0.05  1.78  1.27  1.    0.    0.    0.    1.  ]
 [ 1.28 -0.58 -0.39  0.    1.    0.    1.    0.  ]
 [-1.17  0.21  0.4   1.    0.    0.    0.    1.  ]
 [ 0.05 -0.58 -0.83  0.    1.    1.    0.    0.  ]
 [ 1.28  1.    1.09  1.    0.    0.    0.    1.  ]
 [-1.17 -1.36 -1.61  1.    0.    0.    1.    0.  ]]
(45, 8)

In [39]:
# example of coloumtransformer on covid test .

In [40]:
from sklearn.impute import SimpleImputer

In [41]:
data_covid = pd.read_csv("covid_toy.csv")

In [42]:
data_covid.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [43]:
data_covid.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train,y_test = train_test_split(data_covid.drop(columns=["has_covid"]),data_covid["has_covid"],test_size=0.2)

In [45]:
X_train

    age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
52   47  Female  100.0  Strong  Bangalore
41   82    Male    NaN    Mild    Kolkata
10   75  Female    NaN    Mild      Delhi
..  ...     ...    ...     ...        ...
20   12    Male   98.0  Strong  Bangalore
51   11  Female  100.0  Strong    Kolkata
29   34  Female    NaN  Strong     Mumbai
77    8  Female  101.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai

[80 rows x 5 columns]

In [46]:
si = SimpleImputer()  # fill all the data
X_train_fever =si.fit_transform(X_train[["fever"]])
X_test_fever = si.fit_transform(X_test[["fever"]])

X_train_fever.shape

(80, 1)

In [47]:
X_train_fever

array([[101.        ],
       [ 98.        ],
       [100.        ],
       [100.86486486],
       [100.86486486],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [103.        ],
       [103.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [103.        ],
       [101.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [100.86486486],
       [104.        ],
       [102.        ],
       [103.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [100.86486486],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.86486486],
       [100.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [100.86486486],
       [101.        ],
       [ 99.        ]])

In [48]:
oe= OrdinalEncoder(categories=[["Mild","Strong"]])  # apply the ordina encoding on cough coloum
x_train_cough =oe.fit_transform(X_train[["cough"]])
x_test_cough =oe.fit_transform(X_test[["cough"]])

x_train_cough.shape

(80, 1)

In [49]:
ohe = OneHotEncoder(drop="first",sparse_output=False)
x_train_gender_city = ohe.fit_transform(X_train[["gender","city"]])

x_test_gender_city=ohe.fit_transform(X_test[["gender","city"]])

x_train_gender_city.shape

(80, 4)

In [50]:
x_train_gender_city

array([[1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
#for age coloum 
x_train_age = X_train.drop(columns=["gender","fever","cough","city"]).values

x_test_age = X_test.drop(columns=["gender","fever","cough","city"]).values

x_train_age.shape

(80, 1)

In [61]:
X_train_tranformed=np.concatenate((x_train_age,X_train_fever,x_train_gender_city,x_train_cough),axis=1)

X_test_tranformed=np.concatenate((x_test_age,X_test_fever,x_test_gender_city,x_test_cough),axis=1)

X_train_tranformed.shape,X_test_tranformed.shape

((80, 7), (20, 7))

In [53]:
# by using the coloum trannsform

In [56]:
transformer=ColumnTransformer(transformers=[
("simpleimp",SimpleImputer(),["fever"]),
("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["gender","city"])
],remainder='passthrough')

In [59]:
transformer.fit_transform(X_train).shape

(80, 7)

In [60]:
transformer.fit_transform(X_test).shape

(20, 7)