In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [32]:
data = {
'Gender':['Male','Female','Male','Female','Male','Female','Male','Female','Male','Female',
          'Male','Female','Male','Female','Male','Female','Male','Female','Male','Female'],

'Study_Method':['Online','Offline','Online','Offline','Online','Offline','Offline','Online','Offline','Offline',
                'Online','Offline','Online','Offline','Online','Offline','Offline','Online','Offline','Offline'],

'Study_Hours':[2,5,3,6,4,7,5,4,6,8,2,7,3,6,4,7,5,4,6,8],

'Exam_Result':['Fail','Pass','Fail','Pass','Fail','Pass','Pass','Fail','Pass','Pass',
               'Fail','Pass','Fail','Pass','Fail','Pass','Pass','Fail','Pass','Pass']
}

In [33]:
data= pd.DataFrame(data)
data.head(2)

   Gender Study_Method  Study_Hours Exam_Result
0    Male       Online            2        Fail
1  Female      Offline            5        Pass

In [34]:
#Encoding by using the map technique
data["Gender"]=data["Gender"].map({"Male":0,"Female":1})
data["Study_Method"]=data["Study_Method"].map({"Online":0,"Offline":1})
data["Exam_Result"]=data["Exam_Result"].map({"Fail":0,"Pass":1})

In [35]:
data.head(5)

   Gender  Study_Method  Study_Hours  Exam_Result
0       0             0            2            0
1       1             1            5            1
2       0             0            3            0
3       1             1            6            1
4       0             0            4            0

In [36]:
correlation = data.corr()
print(correlation)

                Gender  Study_Method  Study_Hours  Exam_Result
Gender        1.000000      0.408248     0.615882     0.408248
Study_Method  0.408248      1.000000     0.845728     1.000000
Study_Hours   0.615882      0.845728     1.000000     0.845728
Exam_Result   0.408248      1.000000     0.845728     1.000000

In [ ]:
# # final conclusion 
# #  Study_Method → strongest relationship
#  Study_Hours → second strongest
#   Gender → weaker relationship