In [189]:
import pandas as pd 
import numpy as np

In [190]:
df = {
    'Candidate_ID': range(101, 121),
    'City': ['Mumbai', 'Pune', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai',
             'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', np.nan, 'Female',
               'Male', 'Female', 'Male', 'Male', 'Female', np.nan, 'Male', 'Female', 'Male', 'Female'],
    'Education_Level': ['Diploma', 'Bachelors', 'Masters', 'Bachelors', 'Diploma', 'Masters', 'Bachelors', 'Diploma', 'Masters', 'Bachelors',
                        'Diploma', 'Masters', 'Bachelors', 'Diploma', 'Masters', 'Bachelors', 'Diploma', 'Masters', 'Bachelors', 'Diploma'],
    'Experience_Years': [2, 5, 1, 10, 3, 8, np.nan, 4, 12, 6, 
                         2, 7, 5, 3, 9, 4, 1, 11, 6, np.nan],
    'Salary_Expectation': [30000, 50000, 60000, 90000, 0, 85000, 55000, 35000, 110000, 58000,
                           32000, 75000, 52000, 38000, 95000, 45000, 28000, 105000, 62000, 40000],
    'Placed': ['Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No',
               'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No']
}

data=pd.DataFrame(df)
data.head(4)

,Candidate_ID,City,Gender,Education_Level,Experience_Years,Salary_Expectation,Placed
0,101,Mumbai,Male,Diploma,2.0,30000,Yes
1,102,Pune,Female,Bachelors,5.0,50000,No
2,103,Mumbai,Female,Masters,1.0,60000,Yes
3,104,Delhi,Male,Bachelors,10.0,90000,Yes

In [191]:
data.isnull().sum()

Candidate_ID          0
City                  0
Gender                2
Education_Level       0
Experience_Years      2
Salary_Expectation    0
Placed                0
dtype: int64

In [192]:
data.shape

(20, 7)

In [193]:
sam_data = data[["Gender"]]

In [194]:
data["Gender"]= data["Gender"].fillna(data["Gender"].mode()[0])
data["Experience_Years"] = data["Experience_Years"].fillna(data["Experience_Years"].mean)
data.isnull().sum()

Candidate_ID          0
City                  0
Gender                0
Education_Level       0
Experience_Years      0
Salary_Expectation    0
Placed                0
dtype: int64

In [195]:
pd.get_dummies(sam_data)

    Gender_Female  Gender_Male
0           False         True
1            True        False
2            True        False
3           False         True
4            True        False
5           False         True
6           False         True
7            True        False
8           False        False
9            True        False
10          False         True
11           True        False
12          False         True
13          False         True
14           True        False
15          False        False
16          False         True
17           True        False
18          False         True
19           True        False

In [ ]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(drop="first",sparse_output=False)
ar =one.fit_transform(sam_data) 
data["encode_gender"] = ar[:,0] 
data.head(1)

,Candidate_ID,City,Gender,Education_Level,Experience_Years,Salary_Expectation,Placed,encode_gender
0,101,Mumbai,Male,Diploma,2.0,30000,Yes,1.0

In [197]:
# label encodeing

In [198]:
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
data["label_encode_education_level"]= lab.fit_transform(data["Education_Level"])
data.head(20)

,Candidate_ID,City,Gender,Education_Level,Experience_Years,Salary_Expectation,Placed,encode_gender,label_encode_education_level
0,101,Mumbai,Male,Diploma,2.0,30000,Yes,1.0,1
1,102,Pune,Female,Bachelors,5.0,50000,No,0.0,0
2,103,Mumbai,Female,Masters,1.0,60000,Yes,0.0,2
3,104,Delhi,Male,Bachelors,10.0,90000,Yes,1.0,0
4,105,Pune,Female,Diploma,3.0,0,No,0.0,1
5,106,Delhi,Male,Masters,8.0,85000,Yes,1.0,2
6,107,Mumbai,Male,Bachelors,<bound method Series.mean of 0 2.0\n1 ...,55000,No,1.0,0
7,108,Pune,Female,Diploma,4.0,35000,No,0.0,1
8,109,Delhi,Female,Masters,12.0,110000,Yes,0.0,2
9,110,Mumbai,Female,Bachelors,6.0,58000,No,0.0,0
10,111,Pune,Male,Diploma,2.0,32000,Yes,1.0,1
11,112,Delhi,Female,Masters,7.0,75000,No,0.0,2
12,113,Mumbai,Male,Bachelors,5.0,52000,Yes,1.0,0
13,114,Pune,Male,Diploma,3.0,38000,Yes,1.0,1
14,115,Delhi,Female,Masters,9.0,95000,No,0.0,2
15,116,Mumbai,Female,Bachelors,4.0,45000,Yes,0.0,0
16,117,Pune,Male,Diploma,1.0,28000,No,1.0,1
17,118,Delhi,Female,Masters,11.0,105000,No,0.0,2
18,119,Mumbai,Male,Bachelors,6.0,62000,Yes,1.0,0
19,120,Pune,Female,Diploma,<bound method Series.mean of 0 2.0\n1 ...,40000,No,0.0,1

In [199]:
from sklearn.preprocessing import OrdinalEncoder
ord = [["Diploma", "Bachelors", "Masters"]]
lab1 = OrdinalEncoder(categories=ord)
data[["ordinal_encode_educational_level"]]= lab1.fit_transform(data[["Education_Level"]])
data.head(2)

,Candidate_ID,City,Gender,Education_Level,Experience_Years,Salary_Expectation,Placed,encode_gender,label_encode_education_level,ordinal_encode_educational_level
0,101,Mumbai,Male,Diploma,2.0,30000,Yes,1.0,1,0.0
1,102,Pune,Female,Bachelors,5.0,50000,No,0.0,0,1.0